artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://github.com/The-Autonomous-Ali/Wine_project/raw/main/winequality-red.csv"
  local_data_file: artifacts/data_ingestion/winequality-red.csv
  



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt