name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # You can choose a different runner OS here
    steps:
      - uses: actions/checkout@v3  # Checks out your code from GitHub
      # (Add your project specific build and test steps here)
      - uses: actions/checkout@v3  # Checkout code again (optional, see note below)
        with:
          fetch-depth: 1  # Only fetch the latest commit (reduces download time)
          submodules: false  # Exclude submodules (if applicable)
          exclude: '**/README.md'  # Exclude README.md file

  deploy:
    runs-on: ubuntu-latest  # You can choose a different runner OS here
    needs: build-and-test  # This job depends on the successful completion of build-and-test
    steps:
      - uses: actions/checkout@v3
      - name: Login to AWS ECR
        uses: aws-actions/aws-ecr-docker-login@v2  # Login to ECR with AWS credentials
        with:
          aws-region: your-aws-region  # Replace with your AWS region
          registry-id: your-account-id.dkr.ecr.your-aws-region.amazonaws.com  # Replace with your ECR registry ID

      - name: Build and push Docker image to ECR
        uses: aws-actions/aws-ecr-docker-push@v2  # Build and push image to ECR
        with:
          aws-region: your-aws-region  # Replace with your AWS region
          repository-name: your-ecr-repository-name  # Replace with your ECR repository name
          image-tag: ${{ github.sha }}  # Use the commit SHA for image tagging
          dockerfile-path: docker/Dockerfile  # Path to your Dockerfile (replace if needed)

      - name: Deploy to AWS using CodeDeploy
        uses: aws-actions/aws-codedeploy@v1  # Deploy using AWS CodeDeploy
        with:
          aws-region: your-aws-region  # Replace with your AWS region
          application-name: your-codedeploy-application-name  # Replace with your CodeDeploy application name
          deployment-group-name: your-codedeploy-deployment-group-name  # Replace with your CodeDeploy deployment group name
          service-role-arn: your-codedeploy-service-role-arn  # Replace with the IAM role ARN for CodeDeploy
          # (Optional) Specify a deployment configuration name if you have one

# You can add additional jobs for post-deployment tasks here
